### ISSUE TITLE
WiFi setup

### ISSUE THREAD

**Issue by thomasjobs** [mp-se/victron-receiver#9]
Upgraded firmware to 0.2.5 today. Unfortunately it's no longer possible to connect to a WiFi network. Have tried both in motorhome and at home. Result: Failed to get wifi scan status.

![2024-12-23_13-59-51](https://github.com/user-attachments/assets/17cb155f-2b82-4a9b-97b8-fb38c3d99997)
![2024-12-23_14-00-21](https://github.com/user-attachments/assets/9153220c-a524-416f-91a9-e76ace9bab25)

**Comment by mp-se** [comment]
Where did you download the version from ? the Release page or directly from the dev stream ? The dev stream is work in progress and not full tested. 

Did you do the update via the upload firmware option in the UI ? It should retain all the configuration settings so everything should work as before? 

I've been running the same version for 2 weeks without any issues. 

In order to troubleshoot this you need to get the serial log from the device via serial cable and some software that can read that data. Putty is one of those that can be used.

**Comment by thomasjobs** [comment]
ok, will troubleshoot…….

**Comment by thomasjobs** [comment]
Downloaded the latest version and flashed the device again........now everything work fine.......strange....

After the weekend I will continue checking the data from the the IP22Charger.

![image](https://github.com/user-attachments/assets/7a7c28c6-88dd-4f4b-a2ab-a4a4819c56f7)

**Comment by mp-se** [comment]
Could have been some issue with previous flashing that can have strange effects
